const GET_USERS = {
  STARTS: "GET_USERS_STARTS",
  SUCCESS: "GET_USERS_SUCCESS",
  FAILURE: "GET_USERS_FAILURE",
};

const CREATE_USER = "CREATE_USER";
const REMOVE_USER = "REMOVE_USER";
const EDIT_USER = "EDIT_USER";
export { GET_USERS, CREATE_USER, REMOVE_USER, EDIT_USER };
